version: "3.8"
services:
  manticore:
    environment:
      TZ: ${APP_TIMEZONE}
    image: manticoresearch/manticore:${MANTICORE_VERSION}
    tty: true
    restart: always
    volumes:
      - ./logs:/var/log/manticore
      - ./data:/var/lib/manticore/data
      - ./etc/sphinx.conf:/etc/manticoresearch/manticore.conf
      - ./etc/sphinx.conf:/etc/sphinxsearch/sphinx.conf
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
    ports:
      - 127.0.0.1:${MANTICORE_MYSQL_PORT}:9306 # mysql
      - 127.0.0.1:${MANTICORE_HTTP_PORT}:9308 # http
      - 127.0.0.1:${MANTICORE_UNIX_PORT}:9312 # binary
      #- 127.0.0.1:${MANTICORE_REPL_PORTS}:9315-9325 # replication
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
